- name: Install Proxmox Debian
  when: ansible_distribution == 'Debian'
  become: yes

  tasks:
    - name: "Configure hostname"
      ansible.builtin.hostname:
        name: "pve01.exampsite.local"
      become: true

    - name : Install multiple packages
      apt: name={{ item }} state=latest update_cache=true
      loop: [curl, gpg, gnupg2, software-properties-common, apt-transport-https, lsb-release, ca-certificates]

    - name: "add proxmox apt-key"
      apt_key:
        url: http://download.proxmox.com/debian/proxmox-release-bookworm.gpg
        state: present

    - name: "add proxmox repository"
      apt_repository:
        repo: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
        state: present 
        filename: pve-install
        update_cache: yes

    - name: "Update Repository cache"
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true

    - name: "add proxmox ceph repository"
      apt_repository:
        repo: ""deb http://download.proxmox.com/debian/ceph-quincy bookworm main""
        state: present 
        filename: ceph
        update_cache: yes

    - name : Install PVE kernel
      apt: name=pve-kernel-6.2 state=latest update_cache=true

    - name: Install Postfix
      apt:
        name: postfix
        state: present

    - name: Configure Postfix
      debconf:
        name: postfix
        question: "postfix/main_mailer_type"
        value: "Local only"
        vtype: "string"
        state: "present"
      with_items:
        - pve01.exampsite.local
    
    - name : Install multiple packages
      apt: name={{ item }} state=latest update_cache=true
      loop: [proxmox-ve, open-iscsi]

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Update Grub2
      ansible.builtin.shell: sudo apt remove linux-image-amd64 'linux-image-6.1*'
    - name: Update Grub2
      ansible.builtin.shell: sudo apt remove os-prober
    
    - name: Reboot the server.
        reboot: