---
- name: Install Proxmox Debian
  become: yes
  hosts: deb12-test2
  become_method: sudo
  vars:
    nginx_user: www-data

  # roles:
  #  - nginx

  tasks:
    # - name: Install Nginx Web Server on Debian Family
    #   apt:
    #     name=nginx
    #     state=latest
    #   when:
    #     ansible_os_family == "Debian"
    #   notify:
    #     - nginx systemd

    - name: "Configure hostname"
      ansible.builtin.hostname:
        name: "pve01.exampsite.local"
      become: true
    - name: Set hosts
      ansible.builtin.shell: echo "192.168.5.66 pve01.exampsite.local pve01" > /etc/hosts

    - name: Install multiple packages
      apt: name={{ item }} state=latest update_cache=true
      loop: [curl, gpg, gnupg2, software-properties-common, apt-transport-https, lsb-release, ca-certificates]

    - name: "add proxmox apt-key"
      apt_key:
        url: http://download.proxmox.com/debian/proxmox-release-bookworm.gpg
        state: present

    - name: "add proxmox repository"
      apt_repository:
        repo: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
        state: present
        filename: pve-install
        update_cache: yes

    - name: "Update Repository cache"
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true

    - name: "add proxmox ceph repository"
      apt_repository:
        repo: "deb http://download.proxmox.com/debian/ceph-quincy bookworm main"
        state: present
        filename: ceph
        update_cache: yes

    - name: Install PVE kernel
      apt: name=pve-kernel-6.2 state=latest update_cache=true

    - name: Install Postfix
      apt:
        name: postfix
        state: present

    - name: Install multiple packages
      apt: name={{ item }} state=latest update_cache=true
      loop: [proxmox-ve, open-iscsi]

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
